"""Add is_current_train in Feedback, and modify MonitoringMetrics & add DatadriftsMetrics

Revision ID: 4f82224569a4
Revises: 0f5f5bc333e8
Create Date: 2026-01-14 11:52:15.527001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f82224569a4'
down_revision: Union[str, Sequence[str], None] = '0f5f5bc333e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_drift_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prediction_drift', sa.Float(), nullable=True),
    sa.Column('target_drift', sa.Float(), nullable=True),
    sa.Column('data_drift', sa.Float(), nullable=True),
    sa.Column('drifted_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_drift_metrics_model_type'), 'data_drift_metrics', ['model_type'], unique=False)
    op.drop_column('monitoring_metrics', 'prediction_drift')
    op.drop_column('monitoring_metrics', 'data_drift')
    op.drop_column('monitoring_metrics', 'target_drift')
    op.add_column('nyc_duration_feedback', sa.Column('is_current_train', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nyc_duration_feedback', 'is_current_train')
    op.add_column('monitoring_metrics', sa.Column('target_drift', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('monitoring_metrics', sa.Column('data_drift', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('monitoring_metrics', sa.Column('prediction_drift', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_data_drift_metrics_model_type'), table_name='data_drift_metrics')
    op.drop_table('data_drift_metrics')
    # ### end Alembic commands ###
