from contextlib import contextmanager
from typing import Generator, Optional
import logging

from uuid import UUID
from sqlmodel import create_engine, Session, SQLModel, select, desc
from api_gateway.app.config import config
from api_gateway.app.models.domain import Prediction, Feedback


logger = logging.getLogger(__name__)


class Database:
    def __init__(self):
        """Initialize database connection with SQLModel."""
        self.db_url = config.DATABASE_URL

        # Create Engine with Connection Pooling
        self.engine = create_engine(
            self.db_url,
            pool_size=20,  # Pool 20 connections
            max_overflow=10,  # Allow 10 more if pool is full
            pool_timeout=30,  # Wait 30s for a connection
            pool_recycle=1800,  # Recycle connections every 30 mins
        )

        # Create tables if they don't exist
        self._init_database()

    def _init_database(self) -> None:
        """Initialize database tables."""
        try:
            SQLModel.metadata.create_all(self.engine)
            logger.info("Initialized database")
        except Exception as e:
            logger.error("Failed to initialize database: %s", e)
            raise

    @contextmanager
    def get_db(self) -> Generator[Session, None, None]:
        """Provide a transactional scope around a series of operations."""
        session = Session(self.engine)
        try:
            yield session
            session.commit()
        except Exception:
            session.rollback()
            raise
        finally:
            session.close()

    def save_inference(self, prediction: Prediction) -> UUID:
        """Save prediction to database using SQLModel."""
        with self.get_db() as session:
            session.add(prediction)
            # No need to commit/refresh to get ID, it's auto-generated by factory if missing
            return prediction.id

    def save_feedback(self, feedback: Feedback):
        """Save feedback to database using SQLModel."""
        with self.get_db() as session:
            session.add(feedback)

    def get_prediction(self, prediction_id: int) -> Optional[Prediction]:
        """Get prediction by ID using SQLModel."""
        with self.get_db() as session:
            statement = select(Prediction).where(Prediction.id == prediction_id)
            result = session.exec(statement).first()
            return result

    def get_last_preds_with_feedback(self, row_count: int) -> list[Prediction]:
        with Session(self.engine) as session:
            statement = (
                select(Prediction, Feedback)
                .join(Prediction.feedback)
                .order_by(desc(Prediction.id))
                .limit(row_count)
            )
            results = session.exec(statement).all()

            preds = []
            for p, f in results:
                p.feedback = f
                preds.append(p)

            return preds


repo = Database()
