"""add model_type to monitoring_metrics

Revision ID: 0f5f5bc333e8
Revises: 5518f8a33f7b
Create Date: 2026-01-13 11:43:44.596343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f5f5bc333e8'
down_revision: Union[str, Sequence[str], None] = '5518f8a33f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_metrics', sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_monitoring_metrics_model_type'), 'monitoring_metrics', ['model_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_metrics_model_type'), table_name='monitoring_metrics')
    op.drop_column('monitoring_metrics', 'model_type')
    # ### end Alembic commands ###
