"""create monitoring_metrics table

Revision ID: 5518f8a33f7b
Revises: 928e80c43cf9
Create Date: 2026-01-13 11:33:36.881870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5518f8a33f7b'
down_revision: Union[str, Sequence[str], None] = '928e80c43cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('prediction_drift', sa.Float(), nullable=True),
    sa.Column('target_drift', sa.Float(), nullable=True),
    sa.Column('data_drift', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('drifted_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitoring_metrics')
    # ### end Alembic commands ###
