{
 "title": "ML Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "model_type",
    "label": "Model",
    "query": "SELECT DISTINCT model_type FROM monitoring_metrics;"
   }
  ]
 },
 "panels": [
  {
   "title": "Data Drift",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  data_drift\nFROM monitoring_metrics\nWHERE model_type = '$model_type'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "RMSE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  rmse\nFROM monitoring_metrics\nWHERE model_type = '$model_type'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "R2 Score",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  r2\nFROM monitoring_metrics\nWHERE model_type = '$model_type'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "MAE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  mae\nFROM monitoring_metrics\nWHERE model_type = '$model_type'\nORDER BY timestamp"
    }
   ]
  }
 ]
}