"""Initial migration

Revision ID: 928e80c43cf9
Revises:
Create Date: 2026-01-12 14:13:45.705889

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "928e80c43cf9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nyc_duration_inferences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tpep_pickup_datetime", sa.DateTime(), nullable=False),
        sa.Column("passenger_count", sa.Integer(), nullable=False),
        sa.Column("pulocationid", sa.Integer(), nullable=False),
        sa.Column("dolocationid", sa.Integer(), nullable=False),
        sa.Column("model_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("predicted_duration", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nyc_duration_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prediction_id", sa.Uuid(), nullable=False),
        sa.Column("dolocationid", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["nyc_duration_inferences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nyc_duration_feedback")
    op.drop_table("nyc_duration_inferences")
    # ### end Alembic commands ###
