apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: mlops_postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: mlops
      sslmode: "disable"
